### ISSUE TITLE
Acuity and range of senses

### ISSUE THREAD

**Issue by TheAsel** [RakuJa/BYBE-DB#10] opened 2024-05-31 19:46 UTC
The fields for "acuity" and "range" of senses isn't parsed. This is especially relevant for "scent", as that information can't be retrieved from anywhere else. An example of this is [Mengkare](https://github.com/foundryvtt/pf2e/blob/master/packs/age-of-ashes-bestiary/mengkare.json).

**Comment by RakuJa** [comment] 2024-12-01 18:45
Duplicate of https://github.com/RakuJa/BYBE-DB/issues/2

**Closed as completed by RakuJa** 2024-12-01 18:45 UTC
Labels: enhancement, creature sheet
